name: Package Application with Pyinstaller
on: workflow_dispatch 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.1
    
   

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: test.py --onefile

    - uses: actions/upload-artifact@v3.1.3
      with:
        name: name-of-artifact
        path: src/dist/windows
